include: package:lint/package.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    avoid_dynamic_calls: true
    prefer_final_locals: true
    no_leading_underscores_for_local_identifiers: false
    require_trailing_commas: true
    curly_braces_in_flow_control_structures: false
    unawaited_futures: true
    prefer_single_quotes: true
analyzer: 
  errors:
    cast_nullable_to_non_nullable: warning
    prefer_single_quotes: warning
    require_trailing_commas: warning
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true