name: json_form
description: A Flutter widget capable of using JSON Schemas to build and customize forms.
version: 0.0.1+1
homepage: https://github.com/juancastillo0/json_form

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  extended_masked_text: ^3.0.1
  cross_file: ^0.3.4+1
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
