name: Deploy Dart Web

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy web
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      # Install webdev
      - run: dart pub global activate webdev

      # Install dependencies
      - run: dart pub get
      
      # Build web
      - run: webdev build -- --delete-conflicting-outputs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

